# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photo_detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_PhotoDetectionWindow(object):
    def setupPhotoUi(self, PhotoWindow):
        PhotoWindow.setObjectName("PhotoWindow")
        PhotoWindow.resize(950, 600)
        self.centralwidget = QtWidgets.QWidget(PhotoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FaceRecognition = QtWidgets.QWidget(self.centralwidget)
        self.FaceRecognition.setGeometry(QtCore.QRect(0, 0,950, 600))
        self.FaceRecognition.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.FaceRecognition.setObjectName("FaceRecognition")
        self.pushButton = QtWidgets.QPushButton(self.FaceRecognition)
        self.pushButton.setGeometry(QtCore.QRect(180, 540, 281, 31))
        self.pushButton.setStyleSheet("background-color:goldenrod;\n"
                                      "font: 14pt \"MS Shell Dlg 2\";\n")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.FaceRecognition)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 540, 281, 31))
        self.pushButton_2.setStyleSheet("background-color:goldenrod;\n"
                                        "font: 14pt \"MS Shell Dlg 2\";\n")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(19, 19, 950, 450))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self._retranslateUi(PhotoWindow)
        QtCore.QMetaObject.connectSlotsByName(PhotoWindow)

    def _retranslateUi(self, PhotoWindow):
        _translate = QtCore.QCoreApplication.translate
        PhotoWindow.setWindowTitle(_translate("PhotoWindow", "Face Detection - Photo"))
        self.pushButton.setText(_translate("MainWindow", "Open file"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))
